const SEARCH_SKILLS_REQUEST = 'SEARCH_SKILLS_REQUEST';
const SEARCH_SKILLS_FAILURE = 'SEARCH_SKILLS_FAILURE';
const SEARCH_SKILLS_SUCCESS = 'SEARCH_SKILLS_SUCCESS';
const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export {
    SEARCH_SKILLS_SUCCESS, SEARCH_SKILLS_REQUEST, SEARCH_SKILLS_FAILURE, CHANGE_SEARCH_FIELD,
}
